resources/js/game_list_element.js

See https://expandeddetails-dot-dipact.appspot.com/ for this in action.

Expandeddetails

---

resources/js/login.js
resources/js/main_menu.js

Created a description to what you're logging into.
Moved the "fake" menu in logical order (settings/logout)

Small touches

---

resources/js/game.js

Updated order icons depending on whether your orders have been submitted or not

Updated order icons

---

resources/js/chat_channel.js

> Enter now sends message
> Chat channel is centered on Desktop
> "New messages" has striped red background, is centered and uses the correct Typography.

Chat annoyances

---

resources/js/order_list.js

Changed the transparency of nations so they are easily distinguishable from orders.

Order list colour change

---

resources/js/game_results.js

@zond could you please look at the TODO?
There is some logic I want to add here to increase the salience of the winner and in case of a draw increase the feeling that a draw can still have a winner because of "most points". .. 
If you could add this then merge, I'd be happy!

Add winner

---

resources/js/chat_menu.js

There are still details that need to be fixed, but for tonight it's okay. 
- Added "You:" in front of your messages
- Removed "Nation:" if not you and just 2 people in the chat (and you're the player).
There are still things to do, e.g. the message read counter vs the amount of people in a channel if not all can be displayed, but for now I'm okay.

Much better chat screen

---

resources/js/chat_channel.js
resources/js/chat_menu.js
resources/js/nation_avatar_group.js

Updated the chat menu and headers to show who is in the chat.

Better chat

---

resources/css/main.css
resources/js/chat_channel.js
resources/js/helpers.js
resources/js/order_list.js

Instead of building on what I did yesterday, I redid what I did yesterday :(
Good things are that Martin went ahead and made the order list human. I love the "humanize" feature - can we add that to everything :)?

Order_list

---

resources/js/order_list.js

- Added flags
- Larger font size for nations

Updated orderlist

---

resources/js/order_list.js

- DIAS button now has padding on iPhone 5
- Prettier

Small details

---

resources/js/dip_map.js
resources/js/game.js
resources/js/order_list.js

I made the orders not take up so much screen size, and be still informative.
We need to make them appear after a certain delay (need to play with it to feel what is good), because now they appear too often. But not too long so that it's not possible to find this by accident.

Probably the ugliest refactor ever

---

web-app/src/components/CreateGameDialog.js
web-app/src/components/GameListElement.js
web-app/src/components/GameMetadata.js

Hi @zond I took a look at the Chat Language feature and updated it a bit.
i couldn't get it all to work:
- The chat icon is misaligned; the size and drawing is okay, but it's like 8px too far down. I can't for the life if me get them on equal height as the other icons (in the GameListElement)
- I disabled the Chat Selection language in the CreateGameDialog IF private and all chat are disabled; however, I couldn't get it to work when public and all three available chats are not selected, I think because Anonymous automatically gets checked. I couldn't debug this.
- I moved Chat Language to the top of the list in the gamemetastate so it's more apparent - otherwise I'm worried people might miss it.

Joren language

---

web-app/src/components/Game.js
web-app/src/components/GamePlayers.js
web-app/src/components/GameResults.js
web-app/src/components/MainMenu.js
web-app/src/components/MetadataDialog.js
web-app/src/components/ProgressDialog.js
web-app/src/components/Start.js
web-app/src/icons.js

Added the FAQ as starting point, redid the game menu and the starting game list.

UX improvements

---

web-app/src/components/Game.js
web-app/src/components/OrderList.js
web-app/src/components/Start.js

Closes: https://github.com/zond/dipact/issues/266

Fix sticky footer orders

---

web-app/package.json
web-app/src/components/NationAvatar.tsx
web-app/src/mockService/handlers.ts
web-app/src/pages/__tests__/Game.test.tsx
web-app/src/pages/__tests__/Orders.test.tsx
web-app/src/setupTests.js
web-app/yarn.lock

Fixes issue where console errors were appearing during tests. Also updates tests to fail if there is a console error or warning.

Remove console errors during tests

---

web-app/src/hooks/useCreateGame.ts
web-app/src/pages/CreateGame.tsx
web-app/src/translations/en/common.json
web-app/src/translations/translateKeys.ts

@johnpooch in this branch I didn't change anything yet and already the string translation doens't work for the private game help text... Or is it working at your side?

Translate CreateGame

---

web-app/src/components/Orders/NationSummary.tsx
web-app/src/pages/Orders.tsx
web-app/src/pages/__tests__/CreateGame.test.tsx
web-app/src/pages/__tests__/Orders.test.tsx
web-app/src/setupTests.js
web-app/src/translations/en/common.json
web-app/src/translations/translateKeys.ts

Closes https://github.com/zond/dipact/issues/349

Translate Orders complete

---

web-app/src/pages/ChatMenu.tsx
web-app/src/pages/__tests__/ChatMenu.test.tsx
web-app/src/translations/en/common.json
web-app/src/translations/translateKeys.ts

Not much content, should be done.

Translate-ChatMenu

---

web-app/package.json
web-app/src/components/NationPreferencesDialog.tsx
web-app/src/components/RenameGameDialog.tsx
web-app/src/components/RescheduleDialog.tsx
web-app/src/pages/GameList.tsx
web-app/src/pages/__tests__/GameList.test.tsx

Closes: https://github.com/zond/dipact/issues/364

Reinstate gamelist tests

---

packages/web-app/src/pages/RouteConfig.ts
packages/web-app/src/pages/Router.tsx

This fixes the issue where links directly to a game aren't working properly.

Update Router to handle game link correctly

---

packages/web-app/public/index.html
packages/web-app/src/components/DipMap.js

This has been live for one month now:
- Clarity seems to be giving some data on users, let's increase traffic.
- The algorithm has been fixed for a while but not implemented. 
Super minor changes, no concerns from Beta; I'm merging it 🗡️

Merge Beta into Master

---

packages/web-app/src/static/js/dippymap.js

This is the merge request for Elegantt Orders.
I saw one hard crash while it was on master that I can't replicate, the other ones have been fixed.
Other issues are minor and can be fixed after more feedback/while on beta.

Prevent critical bug if units are destroyed on coasts
